/* =========================================================
   SI-CORE-V1 : ORACLE DDL + COMMENT FULL SCRIPT
   - PK: VARCHAR2(30) (예: A + System.currentTimeMillis())
   - DATE: 운영 SI 기본
   ========================================================= */

------------------------------------------------------------
-- 0) (선택) 기존 객체 정리: 필요 시 사용
------------------------------------------------------------
-- DROP TABLE TB_ADMIN_ACTION_LOG CASCADE CONSTRAINTS;
-- DROP TABLE TB_LOGIN_HISTORY CASCADE CONSTRAINTS;
-- DROP TABLE TB_MENU_ROLE_MAPPING CASCADE CONSTRAINTS;
-- DROP TABLE TB_ROLE_PERMISSION_MAPPING CASCADE CONSTRAINTS;
-- DROP TABLE TB_USER_ROLE_MAPPING CASCADE CONSTRAINTS;
-- DROP TABLE TB_CODE CASCADE CONSTRAINTS;
-- DROP TABLE TB_CODE_GROUP CASCADE CONSTRAINTS;
-- DROP TABLE TB_MENU CASCADE CONSTRAINTS;
-- DROP TABLE TB_PERMISSION CASCADE CONSTRAINTS;
-- DROP TABLE TB_ROLE CASCADE CONSTRAINTS;
-- DROP TABLE TB_USER CASCADE CONSTRAINTS;

------------------------------------------------------------
-- 1) TB_USER
------------------------------------------------------------
CREATE TABLE TB_USER (
    USER_ID          VARCHAR2(30)    NOT NULL,   -- A + System.currentTimeMillis()
    LOGIN_ID         VARCHAR2(50)    NOT NULL,
    PASSWORD         VARCHAR2(200)   NOT NULL,   -- bcrypt 기준
    USER_NAME        VARCHAR2(50)    NOT NULL,
    EMAIL            VARCHAR2(100),
    PHONE            VARCHAR2(20),
    STATUS_CD        VARCHAR2(20)    NOT NULL,   -- NORMAL / LOCK / WITHDRAW
    LOGIN_FAIL_CNT   NUMBER(3)       DEFAULT 0 NOT NULL,
    LAST_LOGIN_AT    DATE,
    CREATED_AT       DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_AT       DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_TB_USER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT CK_TB_USER_STATUS CHECK (STATUS_CD IN ('NORMAL','LOCK','WITHDRAW'))
);

COMMENT ON TABLE TB_USER IS '사용자 기본 정보';
COMMENT ON COLUMN TB_USER.USER_ID IS '사용자 식별자 (A + System.currentTimeMillis)';
COMMENT ON COLUMN TB_USER.LOGIN_ID IS '로그인 아이디';
COMMENT ON COLUMN TB_USER.PASSWORD IS '비밀번호 해시값';
COMMENT ON COLUMN TB_USER.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN TB_USER.EMAIL IS '이메일 주소';
COMMENT ON COLUMN TB_USER.PHONE IS '전화번호';
COMMENT ON COLUMN TB_USER.STATUS_CD IS '사용자 상태 코드 (NORMAL/LOCK/WITHDRAW)';
COMMENT ON COLUMN TB_USER.LOGIN_FAIL_CNT IS '로그인 실패 횟수';
COMMENT ON COLUMN TB_USER.LAST_LOGIN_AT IS '최종 로그인 일시';
COMMENT ON COLUMN TB_USER.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN TB_USER.UPDATED_AT IS '수정 일시';

------------------------------------------------------------
-- 2) TB_ROLE
------------------------------------------------------------
CREATE TABLE TB_ROLE (
    ROLE_ID      VARCHAR2(30)   NOT NULL,
    ROLE_CODE    VARCHAR2(50)   NOT NULL,
    ROLE_NAME    VARCHAR2(100)  NOT NULL,
    DESCRIPTION  VARCHAR2(200),
    USE_YN       CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_AT   DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_TB_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT CK_TB_ROLE_USE_YN CHECK (USE_YN IN ('Y','N'))
);

COMMENT ON TABLE TB_ROLE IS '권한(역할) 정보';
COMMENT ON COLUMN TB_ROLE.ROLE_ID IS '권한 식별자';
COMMENT ON COLUMN TB_ROLE.ROLE_CODE IS '권한 코드';
COMMENT ON COLUMN TB_ROLE.ROLE_NAME IS '권한 명';
COMMENT ON COLUMN TB_ROLE.DESCRIPTION IS '권한 설명';
COMMENT ON COLUMN TB_ROLE.USE_YN IS '사용 여부';
COMMENT ON COLUMN TB_ROLE.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN TB_ROLE.UPDATED_AT IS '수정 일시';

------------------------------------------------------------
-- 3) TB_PERMISSION
------------------------------------------------------------
CREATE TABLE TB_PERMISSION (
    PERMISSION_ID    VARCHAR2(30)   NOT NULL,
    PERMISSION_CODE  VARCHAR2(80)   NOT NULL,
    PERMISSION_NAME  VARCHAR2(100)  NOT NULL,
    DESCRIPTION      VARCHAR2(200),
    USE_YN           CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT       DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_PERMISSION PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT UK_TB_PERMISSION_CODE UNIQUE (PERMISSION_CODE),
    CONSTRAINT CK_TB_PERMISSION_USE_YN CHECK (USE_YN IN ('Y','N'))
);

COMMENT ON TABLE TB_PERMISSION IS '기능 단위 권한 정보';
COMMENT ON COLUMN TB_PERMISSION.PERMISSION_ID IS '기능 권한 식별자';
COMMENT ON COLUMN TB_PERMISSION.PERMISSION_CODE IS '기능 권한 코드';
COMMENT ON COLUMN TB_PERMISSION.PERMISSION_NAME IS '기능 권한 명';
COMMENT ON COLUMN TB_PERMISSION.DESCRIPTION IS '기능 권한 설명';
COMMENT ON COLUMN TB_PERMISSION.USE_YN IS '사용 여부';
COMMENT ON COLUMN TB_PERMISSION.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN TB_PERMISSION.UPDATED_AT IS '수정 일시';

------------------------------------------------------------
-- 4) TB_MENU
------------------------------------------------------------
CREATE TABLE TB_MENU (
    MENU_ID         VARCHAR2(30)   NOT NULL,
    MENU_NAME       VARCHAR2(100)  NOT NULL,
    PARENT_MENU_ID  VARCHAR2(30),
    MENU_LEVEL      NUMBER(2)      NOT NULL,
    SORT_ORDER      NUMBER(5)      DEFAULT 0 NOT NULL,
    MENU_URL        VARCHAR2(200),
    USE_YN          CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT CK_TB_MENU_PARENT CHECK (PARENT_MENU_ID IS NULL OR PARENT_MENU_ID <> MENU_ID),
    CONSTRAINT CK_TB_MENU_LEVEL CHECK (MENU_LEVEL BETWEEN 1 AND 10),
    CONSTRAINT CK_TB_MENU_SORT_ORDER CHECK (SORT_ORDER >= 0),
    CONSTRAINT CK_TB_MENU_USE_YN CHECK (USE_YN IN ('Y','N'))
);

COMMENT ON TABLE TB_MENU IS '메뉴 정보';
COMMENT ON COLUMN TB_MENU.MENU_ID IS '메뉴 식별자';
COMMENT ON COLUMN TB_MENU.MENU_NAME IS '메뉴 명';
COMMENT ON COLUMN TB_MENU.PARENT_MENU_ID IS '상위 메뉴 ID';
COMMENT ON COLUMN TB_MENU.MENU_LEVEL IS '메뉴 레벨';
COMMENT ON COLUMN TB_MENU.SORT_ORDER IS '정렬 순서';
COMMENT ON COLUMN TB_MENU.MENU_URL IS '메뉴 URL';
COMMENT ON COLUMN TB_MENU.USE_YN IS '사용 여부';
COMMENT ON COLUMN TB_MENU.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN TB_MENU.UPDATED_AT IS '수정 일시';

------------------------------------------------------------
-- 5) TB_CODE_GROUP
------------------------------------------------------------
CREATE TABLE TB_CODE_GROUP (
    CODE_GROUP_ID VARCHAR2(30)   NOT NULL,
    GROUP_CODE    VARCHAR2(50)   NOT NULL,
    GROUP_NAME    VARCHAR2(100)  NOT NULL,
    DESCRIPTION   VARCHAR2(200),
    USE_YN        CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_CODE_GROUP PRIMARY KEY (CODE_GROUP_ID),
    CONSTRAINT UK_TB_CODE_GROUP_CODE UNIQUE (GROUP_CODE),
    CONSTRAINT CK_TB_CODE_GROUP_USE_YN CHECK (USE_YN IN ('Y','N'))
);

COMMENT ON TABLE TB_CODE_GROUP IS '공통 코드 그룹';
COMMENT ON COLUMN TB_CODE_GROUP.CODE_GROUP_ID IS '코드 그룹 식별자';
COMMENT ON COLUMN TB_CODE_GROUP.GROUP_CODE IS '코드 그룹 코드';
COMMENT ON COLUMN TB_CODE_GROUP.GROUP_NAME IS '코드 그룹 명';
COMMENT ON COLUMN TB_CODE_GROUP.DESCRIPTION IS '코드 그룹 설명';
COMMENT ON COLUMN TB_CODE_GROUP.USE_YN IS '사용 여부';
COMMENT ON COLUMN TB_CODE_GROUP.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN TB_CODE_GROUP.UPDATED_AT IS '수정 일시';

------------------------------------------------------------
-- 6) TB_CODE
------------------------------------------------------------
CREATE TABLE TB_CODE (
    CODE_ID        VARCHAR2(30)  NOT NULL,
    CODE_GROUP_ID  VARCHAR2(30)  NOT NULL,
    CODE           VARCHAR2(50)  NOT NULL,
    CODE_NAME      VARCHAR2(100) NOT NULL,
    SORT_ORDER     NUMBER(5)     DEFAULT 0 NOT NULL,
    USE_YN         CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_CODE PRIMARY KEY (CODE_ID),
    CONSTRAINT UK_TB_CODE UNIQUE (CODE_GROUP_ID, CODE),
    CONSTRAINT CK_TB_CODE_USE_YN CHECK (USE_YN IN ('Y','N'))
);

COMMENT ON TABLE TB_CODE IS '공통 코드';
COMMENT ON COLUMN TB_CODE.CODE_ID IS '코드 식별자';
COMMENT ON COLUMN TB_CODE.CODE_GROUP_ID IS '코드 그룹 ID';
COMMENT ON COLUMN TB_CODE.CODE IS '코드 값';
COMMENT ON COLUMN TB_CODE.CODE_NAME IS '코드 명';
COMMENT ON COLUMN TB_CODE.SORT_ORDER IS '정렬 순서';
COMMENT ON COLUMN TB_CODE.USE_YN IS '사용 여부';
COMMENT ON COLUMN TB_CODE.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN TB_CODE.UPDATED_AT IS '수정 일시';

------------------------------------------------------------
-- 7) TB_USER_ROLE (mapping)
------------------------------------------------------------
CREATE TABLE TB_USER_ROLE_MAPPING (
    USER_ROLE_ID VARCHAR2(30) NOT NULL,
    USER_ID      VARCHAR2(30) NOT NULL,
    ROLE_ID      VARCHAR2(30) NOT NULL,
    CREATED_AT   DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT UK_TB_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

COMMENT ON TABLE TB_USER_ROLE_MAPPING IS '사용자-권한 매핑';
COMMENT ON COLUMN TB_USER_ROLE_MAPPING.USER_ROLE_ID IS '사용자-권한 매핑 식별자';
COMMENT ON COLUMN TB_USER_ROLE_MAPPING.USER_ID IS '사용자 ID';
COMMENT ON COLUMN TB_USER_ROLE_MAPPING.ROLE_ID IS '권한 ID';
COMMENT ON COLUMN TB_USER_ROLE_MAPPING.CREATED_AT IS '생성 일시';

------------------------------------------------------------
-- 8) TB_ROLE_PERMISSION (mapping)
------------------------------------------------------------
CREATE TABLE TB_ROLE_PERMISSION_MAPPING (
    ROLE_PERMISSION_ID VARCHAR2(30) NOT NULL,
    ROLE_ID            VARCHAR2(30) NOT NULL,
    PERMISSION_ID      VARCHAR2(30) NOT NULL,
    CREATED_AT         DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_ROLE_PERMISSION PRIMARY KEY (ROLE_PERMISSION_ID),
    CONSTRAINT UK_TB_ROLE_PERMISSION UNIQUE (ROLE_ID, PERMISSION_ID)
);

COMMENT ON TABLE TB_ROLE_PERMISSION_MAPPING IS '권한-기능 권한 매핑';
COMMENT ON COLUMN TB_ROLE_PERMISSION_MAPPING.ROLE_PERMISSION_ID IS '권한-기능 매핑 식별자';
COMMENT ON COLUMN TB_ROLE_PERMISSION_MAPPING.ROLE_ID IS '권한 ID';
COMMENT ON COLUMN TB_ROLE_PERMISSION_MAPPING.PERMISSION_ID IS '기능 권한 ID';
COMMENT ON COLUMN TB_ROLE_PERMISSION_MAPPING.CREATED_AT IS '생성 일시';

------------------------------------------------------------
-- 9) TB_MENU_ROLE (mapping)
------------------------------------------------------------
CREATE TABLE TB_MENU_ROLE_MAPPING (
    MENU_ROLE_ID VARCHAR2(30) NOT NULL,
    MENU_ID      VARCHAR2(30) NOT NULL,
    ROLE_ID      VARCHAR2(30) NOT NULL,
    CREATED_AT   DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_MENU_ROLE PRIMARY KEY (MENU_ROLE_ID),
    CONSTRAINT UK_TB_MENU_ROLE UNIQUE (MENU_ID, ROLE_ID)
);

COMMENT ON TABLE TB_MENU_ROLE_MAPPING IS '메뉴-권한 매핑';
COMMENT ON COLUMN TB_MENU_ROLE_MAPPING.MENU_ROLE_ID IS '메뉴-권한 매핑 식별자';
COMMENT ON COLUMN TB_MENU_ROLE_MAPPING.MENU_ID IS '메뉴 ID';
COMMENT ON COLUMN TB_MENU_ROLE_MAPPING.ROLE_ID IS '권한 ID';
COMMENT ON COLUMN TB_MENU_ROLE_MAPPING.CREATED_AT IS '생성 일시';

------------------------------------------------------------
-- 10) TB_LOGIN_HISTORY
------------------------------------------------------------
CREATE TABLE TB_LOGIN_HISTORY (
    LOGIN_HISTORY_ID VARCHAR2(30) NOT NULL,
    USER_ID          VARCHAR2(30) NOT NULL,
    LOGIN_IP         VARCHAR2(45),
    LOGIN_AT         DATE         DEFAULT SYSDATE NOT NULL,
    SUCCESS_YN       CHAR(1)      NOT NULL,
    CONSTRAINT PK_TB_LOGIN_HISTORY PRIMARY KEY (LOGIN_HISTORY_ID),
    CONSTRAINT CK_TB_LOGIN_HISTORY_SUCCESS CHECK (SUCCESS_YN IN ('Y','N'))
);

COMMENT ON TABLE TB_LOGIN_HISTORY IS '로그인 이력';
COMMENT ON COLUMN TB_LOGIN_HISTORY.LOGIN_HISTORY_ID IS '로그인 이력 식별자';
COMMENT ON COLUMN TB_LOGIN_HISTORY.USER_ID IS '사용자 ID';
COMMENT ON COLUMN TB_LOGIN_HISTORY.LOGIN_IP IS '로그인 IP';
COMMENT ON COLUMN TB_LOGIN_HISTORY.LOGIN_AT IS '로그인 일시';
COMMENT ON COLUMN TB_LOGIN_HISTORY.SUCCESS_YN IS '로그인 성공 여부';

------------------------------------------------------------
-- 11) TB_ADMIN_ACTION_LOG
------------------------------------------------------------
CREATE TABLE TB_ADMIN_ACTION_LOG (
    ACTION_LOG_ID  VARCHAR2(30)  NOT NULL,
    USER_ID        VARCHAR2(30)  NOT NULL,   -- 행위자(관리자)
    ACTION_TYPE    VARCHAR2(10)  NOT NULL,   -- INSERT/UPDATE/DELETE
    TARGET_TABLE   VARCHAR2(50)  NOT NULL,
    TARGET_ID      VARCHAR2(60),
    BEFORE_VALUE   CLOB,
    AFTER_VALUE    CLOB,
    ACTION_AT      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_ADMIN_ACTION_LOG PRIMARY KEY (ACTION_LOG_ID),
    CONSTRAINT CK_TB_ADMIN_ACTION_LOG_TYPE CHECK (ACTION_TYPE IN ('INSERT','UPDATE','DELETE'))
);

COMMENT ON TABLE TB_ADMIN_ACTION_LOG IS '관리자 작업 이력';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.ACTION_LOG_ID IS '관리자 작업 이력 식별자';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.USER_ID IS '작업 수행 관리자 ID';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.ACTION_TYPE IS '작업 유형 (INSERT/UPDATE/DELETE)';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.TARGET_TABLE IS '대상 테이블 명';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.TARGET_ID IS '대상 데이터 ID';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.BEFORE_VALUE IS '변경 전 값';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.AFTER_VALUE IS '변경 후 값';
COMMENT ON COLUMN TB_ADMIN_ACTION_LOG.ACTION_AT IS '작업 수행 일시';

------------------------------------------------------------
-- 12) (선택) 실무 최소 인덱스
------------------------------------------------------------
CREATE INDEX IDX_TB_MENU_PARENT ON TB_MENU (PARENT_MENU_ID);
CREATE INDEX IDX_TB_LOGIN_HIS_USER_AT ON TB_LOGIN_HISTORY (USER_ID, LOGIN_AT);
CREATE INDEX IDX_TB_ADMIN_LOG_USER_AT ON TB_ADMIN_ACTION_LOG (USER_ID, ACTION_AT);


