/* =========================================================
   SI-CORE-V1 : ORACLE DML
========================================================= */

-- 그룹코드
INSERT INTO TB_CODE_GROUP
(GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CO_USER_STATUS', '사용자 상태', '사용자 상태', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE_GROUP
(GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CO_ROLE', '역할', '역할', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE_GROUP
(GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CO_PERMISSION', '행위 권한', '행위 권한', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE_GROUP
(GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CO_MENU_TYPE', '메뉴 타입', '메뉴 타입', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE_GROUP
(GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CO_JOB_TYPE', '이벤트 타입', '이벤트 타입', 'Y' , SYSDATE , SYSDATE );

--------------------------------------------------------------------------------------------------------------------------------------------------

-- 공통코드
----사용자 상태 코드
INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('NORMAL', 'CO_USER_STATUS', '정상', '1', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('LOCK', 'CO_USER_STATUS', '잠금', '2', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('WITHDRAW', 'CO_USER_STATUS', '탈퇴', '3', 'Y' , SYSDATE , SYSDATE );
---- 역할
INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('ADMIN', 'CO_ROLE', '관리자', '1', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('MANAGER', 'CO_ROLE', '매니저', '2', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('USER', 'CO_ROLE', '일반 사용자', '3', 'Y' , SYSDATE , SYSDATE );
    -- 행위 권한
INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('READ', 'CO_PERMISSION', '조회', '1', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CREATE', 'CO_PERMISSION', '생성', '2', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('UPDATE', 'CO_PERMISSION', '수정', '3', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('DELETE', 'CO_PERMISSION', '삭제', '4', 'Y' , SYSDATE , SYSDATE );

---- 메뉴 타입
INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('SCREEN', 'CO_MENU_TYPE', '화면', '1', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('POPUP', 'CO_MENU_TYPE', '팝업', '2', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('LINK', 'CO_MENU_TYPE', '링크', '3', 'Y' , SYSDATE , SYSDATE );

---- 이벤트 타입
INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('LOGIN', 'CO_JOB_TYPE', '로그인', '1', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('LOGOUT', 'CO_JOB_TYPE', '로그아웃', '2', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('CREATE', 'CO_JOB_TYPE', '생성', '3', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('UPDATE', 'CO_JOB_TYPE', '수정', '4', 'Y' , SYSDATE , SYSDATE );

INSERT INTO TB_CODE
(CODE, GROUP_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
VALUES('DELETE', 'CO_JOB_TYPE', '삭제', '5', 'Y' , SYSDATE , SYSDATE );








